package PASO;

public enum Provincia {
    BUENOS_AIRES, MISIONES, TIERRA_DEL_FUEGO, CHACO, ENTRE_RIOS, LA_PAMPA, CORDOBA, SANTA_FE, SANTA_CRUZ, MENDOZA,
    TUCUMAN, SALTA, JUJUY, CORRIENTES, NEUQUEN, RIO_NEGRO, SAN_JUAN, CHUBUT, FORMOSA, LA_RIOJA, SAN_LUIS,  SANTIAGO_DEL_ESTERO,
    CATAMARCA
}
